// src/app/models.ts

export interface Permission {
    _id: any; // ID generated by the backend
    name: string; // Permission name
}

export interface Role {
    _id: any; // ID generated by the backend
    name: string; // Role name (e.g., 'admin', 'doctor')
    permissions: Permission[]; // Array of permissions assigned to this role
}

export interface User {
    _id: any; // ID generated by the backend
    email: string; // User email
    role: Role; // Role object (references the Role interface)
    isDeleted: boolean; // Indicates if the user is deleted
    // Add other user fields if necessary
}

export interface Specialty {

    _id: any; // ID generated by the backend
    name: string; // Specialty name (e.g., 'Cardiology')
    isDeleted: boolean; // Whether this specialty is deleted
}


export interface Doctor {
    id: string;
    doctorId?: any,
    doctorName: string,
    firstName: string,
    lastName: string,
    speciality:any,
    contactNumber: string;
    consultancyFees: number;
    yearsOfExperience: number; // in years
    averageRating: number; // number of reviews
    earnings: any; // total earnings
    profileImg?: any; // Optional field for profile image
    about?: string;
    degree?: string;
    licenseNumber?: string;
    availabilityDays?: any; // New field for availability days
    availability?: any;
    timeSlot?: any; // New field for time slot
    email?: string; // New field for email
  }

  export interface Patient {
    userId: string;
    firstName: string;
    lastName: string;
    age: number;
    gender: string;
    bloodGroup: string;
    maritalStatus: string;
    contactNumber: string;
    address: string;
    city: string;
    state: string;
    profileImg?: {
      public_id: string;
      url: string;
    };
    isDeleted: boolean;
    
lastAppointmentDate:any;

totalAppointmentsCount:number;

  }
  

  export interface Appointment {
    appointmentId: string;
    patientName: string;
    appointmentDate: string;
    doctorId: string;  // Make sure doctorId is part of the appointment
    doctorName?: string;
    specialty?: string;
    status: string;
  }
  
  